spring:
  application:
    name: api-gateway        # ✅ config server uses this to find api-gateway.yml
  config:
    import: configserver:http://localhost:9090/

server:
  port: 9000

logging:
  level:
    root: INFO
    com.dailyexpensetracker.apigateway: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG